name: ci:type-check
on:
  - push
  - pull_request
jobs:
  type-check:
    name: Continuous integration (type checking)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install 📦
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --ignore-scripts
          useRollingCache: true

      - name: TypeScript check ☑️
        run: yarn tsc
